name: Publish Development Build
on: push

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-java@v2
              with:
                  java-version: 17
                  distribution: adopt
            - name: Build
              run: ./gradlew build
